project:
  type: website

website:
  title: "Population Dynamics Analysis"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: report.qmd
        text: Final Report
format:
  html:
    theme: cosmo
    toc: true          
    toc-depth: 2       
    number-sections: true

output-dir: docs